export enum FormFieldType {
  date = 'date',
  text = 'text',
  textarea = 'textarea',
  typeahead = 'typeahead',
  photo = 'photo',
  multiselect = 'multiselect',
  select = 'select',
  checkbox = 'checkbox',
  toggle = 'toggle',
  radio = 'radio',
  textlist = 'textlist',
  dashed = 'dashed',
  number = 'number',
  message = 'message',
  editor = 'editor',
  time = 'time',
  multifield = 'multifield',
  action = 'action',
  currency = 'currency',
  banner = 'banner',
  percentage = 'percentage',
  multiselectdropdown = 'multiselectdropdown',
}
